language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -U wheel
  - pip install -r requirements.txt

cache:
  directories:
  - "$HOME/.cache/pip"

script: nosetests --with-coverage tests
