language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

cache:
  directories:
  - "$HOME/.cache/pip"
  - lib/python3.3/site-packages
  - lib/python3.4/site-packages
  - lib/python3.5/site-packages
  - lib/python3.6/site-packages

script: nosetests --with-coverage tests

notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    secure: Mdy0pgux/YjCky+k/QCEHrNj9iTeCo2qD7DP0SyuO93KzVBWjH5H25rR38pKFnUA3eRbbRiXijXh641TVZ5wTWRWuP+CuXmVtuCAsp4A6Bb87pOM6YbGA9fgjwYsDdgPn4bGAM9uzZYDqdbiWQ0B6ae2NsFJzQimpPTQxsQcgVg=
